feat/5-registration-page
Hikki-s/ForestTalkClient pull request #10
Opened 2024-10-24 07:05 UTC by KirillKamratov

[WIP]: Registration

2024-10-24 15:30 UTC, Hikki-s commented on src/app/auth/register/register.component.html
> +        ></tui-error>
Сделай кастомный валидатор для проверки пароля

function passwordsMatchValidator(): ValidatorFn {
  return (control: AbstractControl): ValidationErrors | null
  
 И через control.get получи нужные 
 
 Сделай проверку что если поле Подтвердите пароль пустое то null если что-то набрано то проверку соответствия.

2024-10-24 15:32 UTC, Hikki-s commented on src/app/auth/register/register.component.ts
> +        validators: [Validators.required, Validators.email],
Сделай кастомный валидатор email, на регулярку ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$

2024-10-29 14:03 UTC, mkozakevich requested changes

2024-10-29 14:03 UTC, mkozakevich commented on src/app/auth/register/register.component.ts
> +        validators: [Validators.required, ageValidator],
почему бы просто не указать min max в tui-input-date? зачем писать собственный валидатор, когда все без него делается в две строки?)

2024-10-29 14:03 UTC, mkozakevich commented on src/app/auth/shared/services/registration/registration.service.ts
> +  private readonly ApiURL = "https://forest-talk-api.onrender.com/api/auth";
можно вообще константой за пределами класса положить

2024-10-30 19:11 UTC, merged